repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-broken-line,
            flake8-bugbear,
            flake8-comprehensions,
            flake8-docstrings,
            pydocstyle,
            flake8-eradicate,
            flake8-print,
            flake8_builtins,
            flake8_isort,
            flake8_simplify,
            mccabe,
            pycodestyle,
            pyflakes,
          ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
